name: stock-dashboard-app
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pyqt=5.15.9
  - pyqtwebengine=5.15.9
  - pip
  - pip:
      # - flet
      # - streamlit
      - yfinance
      - scikit-learn
      - matplotlib
      - plotly
      # - kaleido
      - pytest
      - pyinstaller